task_id:"xswPpIQjS7O_RZEHLmbtd" situation_id:"mCGHaS6eKADWHXJNW-VVt" check_item:{check_item_id:"pEzWRc7wAaFyrSSUXkqq1" command:{command_id:"JbSzzf31bPjKRxXI6LH96" command_line:"progate diagnose"} command:{command_id:"-u5VMoxqivTwvoblXmx5x" command_line:"bash ./.progate/check_puppeteer.sh"}} check_item:{check_item_id:"N7gGj3hFZZbbruxEo3vR0" command:{command_id:"Eqg1JZbARIainQAzi10Do" command_line:"npm run test:tab"}} check_item:{check_item_id:"-WsdvOCPE7xflvl8h84rZ" command:{command_id:"5Ta1q7zPkLB5OZ-Skq9-m" command_line:"npm run test:display"}} check_item:{check_item_id:"f7Zde_MrcFvBwt9lJ15he" command:{command_id:"0XvI6g4wX5VqDBrLTFTsA" command_line:"npm run test:toggle"}}